name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      # Install rbenv
      - name: Install rbenv
        run: |
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          exec $SHELL

      # Install Ruby using rbenv
      - name: Install Ruby
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
          exec $SHELL
          rbenv install 3.0.3
          rbenv global 3.0.3
          ruby -v

      - name: Install mustache (to update the date)
        run: gem install mustache

      - name: creates output
        run: sh ./build.sh

      # Clone the destination repository
      - name: Clone destination repository
        run: git clone https://github.com/${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}/Inha-Metaverse-Frontend.git output

      # Push to the destination repository
      - name: Push to another repository
        run: |
          cd output
          git config user.name "${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}"
          git config user.email "${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}"
          git add .
          git commit -m "Update from main repository"
          git push --force "https://${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}:${{ secrets.PERSONAL_REPO_SECRETE_FOR_VERCEL }}@github.com/${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}/Inha-Metaverse-Frontend.git" main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
