name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh

      # Add the following steps to initialize and push to the personal repository
      - name: Initialize and push to personal repository
        run: |
          git init
          git config user.name "${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}"
          git config user.email "${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}"
          git add .
          git commit -m "Initial commit"
          git push --force "https://${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}:${{ secrets.PERSONAL_REPO_SECRETE_FOR_VERCEL }}@github.com/yerim216/vpspace_web.git" main

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_REPO_SECRETE_FOR_VERCEL }}
        with:
          source-directory: 'output'
          destination-github-username: "${{ secrets.OFFICIAL_ACCOUNT_USERNAME }}"
          destination-repository-name: vpspace_web
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
